name: Static Analysis with CodeQL and Dependency Review

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]  # Trigger on PR open, sync, and reopen events

permissions:
  contents: read
  pull-requests: write

jobs:
  # Job 1: CodeQL Static Analysis
  codeql-analysis:
    name: Static Analysis with CodeQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python
          queries: security-extended  # Use extended security queries for analysis

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  # Job 2: Dependency Review
  dependency-review:
    if: github.event_name == 'pull_request' 
    name: Dependency Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Dependency Review
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high  # Fail on high and critical severity vulnerabilities
          vulnerability-check: true  # Perform vulnerability checks
          comment-summary-in-pr: on-failure  # Only add a comment to the PR if vulnerabilities are found
          fail-on-scopes: runtime  # Fail only for vulnerabilities in runtime dependencies
