name: Prevent Push on High and Critical Severity Vulnerabilities

on:
  push:
    branches:
      - main  # Or any other branch where you want to enforce this

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  dependabot:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Fetch Dependabot alerts
      - name: Fetch Dependabot Alerts
        id: alerts
        run: |
          dependabot_alerts=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/dependabot/alerts")

          # Check for high or critical severity vulnerabilities
          high_or_critical_alerts=$(echo "$dependabot_alerts" | jq '. | map(select(.severity == "high" or .severity == "critical")) | length')

          # Output high or critical alerts count for debugging
          echo "High or Critical-risk alerts found: $high_or_critical_alerts"

          # Fail the workflow if there are high or critical-risk vulnerabilities
          if [ "$high_or_critical_alerts" -gt 0 ]; then
            echo "::error ::High or Critical-risk vulnerabilities found: $high_or_critical_alerts"
            exit 1  # This will cause the push to fail
          fi
