name: Dependabot Security Check

on:
  pull_request:
    branches:
      - main  # Or whatever your protected branch is

jobs:
  dependabot-alerts:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code to analyze the PR
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Dependabot
      - name: Run Dependabot Security Check
        uses: dependabot-action/dependabot-action@v1
        with:
          # Add this action to check Dependabot alerts directly
          dependabot-version: "2"  # Use Dependabot version 2 for security alerts

      # Step 3: Fail if there are any high-severity alerts
      - name: Fail if High Severity Dependabot Alerts Exist
        run: |
          alerts=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/dependabot/alerts")

          high_risk_alerts=$(echo "$alerts" | jq '. | map(select(.severity == "high")) | length')
          if [ "$high_risk_alerts" -gt 0 ]; then
            echo "Error: Found $high_risk_alerts high-risk Dependabot alerts. Resolve before merging."
            exit 1
          else
            echo "No high-risk Dependabot alerts found. Proceeding with the merge."
          fi
