name: Pylint SARIF Analysis

on: [push, pull_request]

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: pip install pylint
      
      - name: Run pylint and convert to SARIF
        run: |
          python pylint-to-sarif.py my_package/ pylint-output.sarif
      
      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: pylint-output.sarif





