name: Pylint Analysis

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pylint sarif-tools

      - name: Run pylint
        run: |
          pylint --output-format=json my_package/ > pylint-output.json

      - name: Convert JSON to SARIF
        run: |
          json2sarif pylint-output.json > pylint-output.sarif

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: pylint-output.sarif
